In [2]:
# from google.colab import drive
import pandas as pd

import numpy as np
from numpy import mean
from numpy import std
from numpy import ravel

import scipy
import joblib
import re
import glob
import sklearn
from math import sqrt
from decimal import Decimal


from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.model_selection import cross_val_score

from sklearn.model_selection import GridSearchCV

from sklearn.metrics import make_scorer
from sklearn.metrics import mean_squared_error
# from sklearn.metrics import mean_absolute_percentage_error

# import xgboost as xgb
# from xgboost import XGBRegressor

from geopy.exc import GeocoderTimedOut
from geopy.distance import geodesic
from geopy.geocoders import Nominatim

from tqdm import tqdm
import requests

# !pip install CurrencyConverter
# from currency_converter import CurrencyConverter

In [9]:
# YANDEX = 'NUMBER API'
# def get_distance(lat, lon, KREMLIN_LAT, KREMLIN_LON):
#     return round(geodesic((lat, lon), (KREMLIN_LAT, KREMLIN_LON)).km, 2)


# def get_coords(input_address):
#   geodata = requests.get(f'https://geocode-maps.yandex.ru/1.x/?apikey={YANDEX}&geocode={input_address}&format=json').json()
#   lon, lat = geodata['response']['GeoObjectCollection']['featureMember'][0]['GeoObject']['Point']['pos'].split()
#   area_name = geodata['response']['GeoObjectCollection']['featureMember'][0]['GeoObject'].get('metaDataProperty'
#   ).get('GeocoderMetaData').get('AddressDetails').get('Country').get('AdministrativeArea').get('AdministrativeAreaName')
#   address_name = geodata['response']['GeoObjectCollection']['featureMember'][0]['GeoObject'].get('metaDataProperty'
#   ).get('GeocoderMetaData').get('AddressDetails').get('Country').get('AddressLine')
#   return float(lat), float(lon), area_name, address_name

In [12]:
# get_coords('Москва Новый Арбат 27')

KeyError: 'response'

In [89]:
# Визуализация
import seaborn as sns

import matplotlib.pyplot as plt

# from mlxtend.plotting import plot_decision_regions

from mpl_toolkits.mplot3d import Axes3D

plt.rcParams['figure.dpi'] = 150
plt.style.use('seaborn-deep')
pd.set_option('display.max_columns', None)

In [ ]:
!

In [3]:
path = "cian.csv"

In [45]:
df = pd.read_csv(path)

In [5]:
df.head()

,Unnamed: 0,ID объявления,Количество комнат,Тип,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,...,Окна,Санузел,Можно с детьми/животными,Дополнительно,Название ЖК,Серия дома,"Высота потолков, м",Лифт,Мусоропровод,Ссылка на объявление
0,0,271271157,4,Квартира,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",...,NaN,NaN,"Можно с детьми, Можно с животными","Мебель в комнатах, Мебель на кухне, Ванна, Душ...","Новый Арбат, 2010",NaN,3.0,"Пасс (4), Груз (1)",Да,https://www.cian.ru/rent/flat/271271157
1,1,271634126,4,Квартира,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",...,На улицу и двор,"Совмещенный (2), Раздельный (1)",Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.5,"Пасс (1), Груз (1)",Нет,https://www.cian.ru/rent/flat/271634126
2,2,271173086,"4, Оба варианта",Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",...,На улицу и двор,Совмещенный (3),Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.2,Пасс (1),NaN,https://www.cian.ru/rent/flat/271173086
3,3,272197456,"4, Оба варианта",Квартира,м. Смоленская (3 мин пешком),"Москва, переулок Плотников, 21С1",170.0/95.0/17.0,5/6,подземная,"400000.0 руб./ За месяц, Залог - 400000 руб., ...",...,На улицу и двор,Совмещенный (3),Можно с животными,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",NaN,NaN,3.2,Пасс (1),NaN,https://www.cian.ru/rent/flat/272197456
4,4,273614615,2,Квартира,м. Арбатская (7 мин пешком),"Москва, улица Новый Арбат, 15",58.0/38.0/5.0,"12/26, Панельный",NaN,"225000.0 руб./ За месяц, Залог - 225000 руб., ...",...,На улицу и двор,Совмещенный (2),NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",The Book,NaN,3.9,"Пасс (1), Груз (1)",Да,https://www.cian.ru/rent/flat/273614615

In [46]:
df = df[['Количество комнат', 'Метро', 'Цена', 'Окна']]
df

,Количество комнат,Метро,Цена,Окна
0,4,м. Смоленская (9 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",NaN
1,4,м. Смоленская (8 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",На улицу и двор
2,"4, Оба варианта",м. Смоленская (7 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",На улицу и двор
3,"4, Оба варианта",м. Смоленская (3 мин пешком),"400000.0 руб./ За месяц, Залог - 400000 руб., ...",На улицу и двор
4,2,м. Арбатская (7 мин пешком),"225000.0 руб./ За месяц, Залог - 225000 руб., ...",На улицу и двор
...,...,...,...,...
23363,NaN,м. Говорово (8 мин пешком),"42000.0 руб./ За месяц, Залог - 42000 руб., Ко...",NaN
23364,1,м. Солнцево (7 мин пешком),"45000.0 руб./ За месяц, Залог - 45000 руб., Ко...",Во двор
23365,"2, Оба варианта",м. Солнцево (6 мин пешком),"50000.0 руб./ За месяц, Залог - 50000 руб., Ко...",На улицу и двор
23366,2,м. Солнцево (11 мин пешком),"55000.0 руб./ За месяц, Залог - 50000 руб., Ко...",Во двор
23367,"2, Оба варианта",м. Говорово (10 мин пешком),"57000.0 руб./ За месяц, Залог - 60000 руб., Ко...",Во двор

In [13]:
df['Количество комнат'].isnull().values.sum()

1041

In [47]:
df = df.assign(rooms = df['Количество комнат'].str[0].astype(float))
df['rooms'].value_counts()

2.0    8466
1.0    7931
3.0    4262
4.0    1163
5.0     367
6.0     138
Name: rooms, dtype: int64

In [48]:
#создаём категориальные значения кол-ва комнат
df = df.assign(rooms = df['Количество комнат'].str[0].astype(float))
df['one_room'] = [1  if x == 1.0 else 0 for x in df['rooms']] 
df['two_room'] = [1  if x == 2.0 else 0 for x in df['rooms']]
df['three_room'] = [1  if x == 3.0 else 0 for x in df['rooms']]
df['four_room'] = [1  if x == 4.0 else 0 for x in df['rooms']]
df['five_room'] = [1  if x == 5.0 else 0 for x in df['rooms']]
df['six_room'] = [1  if x == 6.0 else 0 for x in df['rooms']]
df['rooms'] = df['rooms'].fillna(0)
# df.drop('NaN_room',axis =1)
df['NaN_room'] = [1 if x == 0 else 0 for x in df['rooms']]
df
# df.drop(['Количество комнат', 'rooms'],axis = 1)
# np.NaN

,Количество комнат,Метро,Цена,Окна,rooms,one_room,two_room,three_room,four_room,five_room,six_room,NaN_room
0,4,м. Смоленская (9 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",NaN,4.0,0,0,0,1,0,0,0
1,4,м. Смоленская (8 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",На улицу и двор,4.0,0,0,0,1,0,0,0
2,"4, Оба варианта",м. Смоленская (7 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",На улицу и двор,4.0,0,0,0,1,0,0,0
3,"4, Оба варианта",м. Смоленская (3 мин пешком),"400000.0 руб./ За месяц, Залог - 400000 руб., ...",На улицу и двор,4.0,0,0,0,1,0,0,0
4,2,м. Арбатская (7 мин пешком),"225000.0 руб./ За месяц, Залог - 225000 руб., ...",На улицу и двор,2.0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
23363,NaN,м. Говорово (8 мин пешком),"42000.0 руб./ За месяц, Залог - 42000 руб., Ко...",NaN,0.0,0,0,0,0,0,0,1
23364,1,м. Солнцево (7 мин пешком),"45000.0 руб./ За месяц, Залог - 45000 руб., Ко...",Во двор,1.0,1,0,0,0,0,0,0
23365,"2, Оба варианта",м. Солнцево (6 мин пешком),"50000.0 руб./ За месяц, Залог - 50000 руб., Ко...",На улицу и двор,2.0,0,1,0,0,0,0,0
23366,2,м. Солнцево (11 мин пешком),"55000.0 руб./ За месяц, Залог - 50000 руб., Ко...",Во двор,2.0,0,1,0,0,0,0,0
23367,"2, Оба варианта",м. Говорово (10 мин пешком),"57000.0 руб./ За месяц, Залог - 60000 руб., Ко...",Во двор,2.0,0,1,0,0,0,0,0

In [49]:
cost = df['Цена'].str.split(',', expand=True)
# print(cost)
df['rent_cost'] = cost[0].str.split(' ')
df['rent_cost'] = [float(x[0]) for x in df['rent_cost']]
# df['rent_cost'].dtype
df

,Количество комнат,Метро,Цена,Окна,rooms,one_room,two_room,three_room,four_room,five_room,six_room,NaN_room,rent_cost
0,4,м. Смоленская (9 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",NaN,4.0,0,0,0,1,0,0,0,500000.0
1,4,м. Смоленская (8 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",На улицу и двор,4.0,0,0,0,1,0,0,0,500000.0
2,"4, Оба варианта",м. Смоленская (7 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",На улицу и двор,4.0,0,0,0,1,0,0,0,500000.0
3,"4, Оба варианта",м. Смоленская (3 мин пешком),"400000.0 руб./ За месяц, Залог - 400000 руб., ...",На улицу и двор,4.0,0,0,0,1,0,0,0,400000.0
4,2,м. Арбатская (7 мин пешком),"225000.0 руб./ За месяц, Залог - 225000 руб., ...",На улицу и двор,2.0,0,1,0,0,0,0,0,225000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23363,NaN,м. Говорово (8 мин пешком),"42000.0 руб./ За месяц, Залог - 42000 руб., Ко...",NaN,0.0,0,0,0,0,0,0,1,42000.0
23364,1,м. Солнцево (7 мин пешком),"45000.0 руб./ За месяц, Залог - 45000 руб., Ко...",Во двор,1.0,1,0,0,0,0,0,0,45000.0
23365,"2, Оба варианта",м. Солнцево (6 мин пешком),"50000.0 руб./ За месяц, Залог - 50000 руб., Ко...",На улицу и двор,2.0,0,1,0,0,0,0,0,50000.0
23366,2,м. Солнцево (11 мин пешком),"55000.0 руб./ За месяц, Залог - 50000 руб., Ко...",Во двор,2.0,0,1,0,0,0,0,0,55000.0
23367,"2, Оба варианта",м. Говорово (10 мин пешком),"57000.0 руб./ За месяц, Залог - 60000 руб., Ко...",Во двор,2.0,0,1,0,0,0,0,0,57000.0

In [14]:
df['subway'] = df['Метро'].str.extractall('(\d+)').unstack().fillna('').sum(axis=1).astype(int)
# time_to_subway = [s for s in df['subway'] if s.isdigit()]
# time_to_subway
df['subway'] = df['subway'].fillna(0)
df['NaN_subway'] = [1 if x == 0 else 0 for x in df['subway']]

,Количество комнат,Метро,Цена,Окна,rooms,one_room,two_room,three_room,four_room,five_room,six_room,NaN_room,rent_cost,subway,NaN_subway
0,4,м. Смоленская (9 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",NaN,4.0,0,0,0,1,0,0,0,500000.0,9.0,0
1,4,м. Смоленская (8 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",На улицу и двор,4.0,0,0,0,1,0,0,0,500000.0,8.0,0
2,"4, Оба варианта",м. Смоленская (7 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",На улицу и двор,4.0,0,0,0,1,0,0,0,500000.0,7.0,0
3,"4, Оба варианта",м. Смоленская (3 мин пешком),"400000.0 руб./ За месяц, Залог - 400000 руб., ...",На улицу и двор,4.0,0,0,0,1,0,0,0,400000.0,3.0,0
4,2,м. Арбатская (7 мин пешком),"225000.0 руб./ За месяц, Залог - 225000 руб., ...",На улицу и двор,2.0,0,1,0,0,0,0,0,225000.0,7.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23363,NaN,м. Говорово (8 мин пешком),"42000.0 руб./ За месяц, Залог - 42000 руб., Ко...",NaN,0.0,0,0,0,0,0,0,1,42000.0,8.0,0
23364,1,м. Солнцево (7 мин пешком),"45000.0 руб./ За месяц, Залог - 45000 руб., Ко...",Во двор,1.0,1,0,0,0,0,0,0,45000.0,7.0,0
23365,"2, Оба варианта",м. Солнцево (6 мин пешком),"50000.0 руб./ За месяц, Залог - 50000 руб., Ко...",На улицу и двор,2.0,0,1,0,0,0,0,0,50000.0,6.0,0
23366,2,м. Солнцево (11 мин пешком),"55000.0 руб./ За месяц, Залог - 50000 руб., Ко...",Во двор,2.0,0,1,0,0,0,0,0,55000.0,11.0,0
23367,"2, Оба варианта",м. Говорово (10 мин пешком),"57000.0 руб./ За месяц, Залог - 60000 руб., Ко...",Во двор,2.0,0,1,0,0,0,0,0,57000.0,10.0,0

In [74]:
df['subway'] = df['Метро'].str.split('(', expand=True)[1].str.split(" ", expand=True)[0]
# df['subway']= sub_time.astype(float)
# df['subway'] = df['subway'].fillna(0)
df['nan_sub'] = []
df

KeyError: 1

In [17]:
df['Окна'].value_counts()

Во двор            10870
На улицу и двор     3295
На улицу            2590
Name: Окна, dtype: int64

In [21]:
df['dvor'] = [1 if x == 'Во двор' else 0 for x in df['Окна']]
df['ulitsa'] = [1 if x == 'На улицу' else 0 for x in df['Окна']]
df['ulitsa_dvor'] = [1 if x == 'На улицу и двор' else 0 for x in df['Окна']]
df['Окна'] = df['Окна'].fillna(0)
df['NaN_okna'] = [1 if x == 0 else 0 for x in df['Окна']]

In [22]:
df

,Количество комнат,Метро,Цена,Окна,rooms,one_room,two_room,three_room,four_room,five_room,six_room,NaN_room,rent_cost,subway,NaN_subway,dvor,ulitsa,ulitsa_dvor,NaN_okna
0,4,м. Смоленская (9 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",0,4.0,0,0,0,1,0,0,0,500000.0,9.0,0,0,0,0,1
1,4,м. Смоленская (8 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",На улицу и двор,4.0,0,0,0,1,0,0,0,500000.0,8.0,0,0,0,1,0
2,"4, Оба варианта",м. Смоленская (7 мин пешком),"500000.0 руб./ За месяц, Залог - 500000 руб., ...",На улицу и двор,4.0,0,0,0,1,0,0,0,500000.0,7.0,0,0,0,1,0
3,"4, Оба варианта",м. Смоленская (3 мин пешком),"400000.0 руб./ За месяц, Залог - 400000 руб., ...",На улицу и двор,4.0,0,0,0,1,0,0,0,400000.0,3.0,0,0,0,1,0
4,2,м. Арбатская (7 мин пешком),"225000.0 руб./ За месяц, Залог - 225000 руб., ...",На улицу и двор,2.0,0,1,0,0,0,0,0,225000.0,7.0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23363,NaN,м. Говорово (8 мин пешком),"42000.0 руб./ За месяц, Залог - 42000 руб., Ко...",0,0.0,0,0,0,0,0,0,1,42000.0,8.0,0,0,0,0,1
23364,1,м. Солнцево (7 мин пешком),"45000.0 руб./ За месяц, Залог - 45000 руб., Ко...",Во двор,1.0,1,0,0,0,0,0,0,45000.0,7.0,0,1,0,0,0
23365,"2, Оба варианта",м. Солнцево (6 мин пешком),"50000.0 руб./ За месяц, Залог - 50000 руб., Ко...",На улицу и двор,2.0,0,1,0,0,0,0,0,50000.0,6.0,0,0,0,1,0
23366,2,м. Солнцево (11 мин пешком),"55000.0 руб./ За месяц, Залог - 50000 руб., Ко...",Во двор,2.0,0,1,0,0,0,0,0,55000.0,11.0,0,1,0,0,0
23367,"2, Оба варианта",м. Говорово (10 мин пешком),"57000.0 руб./ За месяц, Залог - 60000 руб., Ко...",Во двор,2.0,0,1,0,0,0,0,0,57000.0,10.0,0,1,0,0,0

In [42]:
df['subway'].isnull().sum()

0